### ISSUE TITLE
⌨️ Rename `component`/s and `service`/s as per the `TODO`s

### ISSUE THREAD

**Issue by usama251993** [usamazansari/itinerary-assistant#107]
### Rename Components and Services in `ViewTrip` Module

---

- [x] Rename `AllTrips*` to `TripList*` in `ViewTripModule`
- [x] Redesign `trip` route in `api` as a module
- [x] Make the routing consistent in NestJS and Angular applications
